### ISSUE TITLE
What are the technical reasons of choosing not to use redis?

### ISSUE THREAD

**Issue by DemGiran** [breejs/bree#12]
Can someone please help me understand? thanks a lot for your time

**Comment by niftylettuce** [comment]
It is widely known that Redis should only be used for caching or session storage (as it is not a persistent data store, and the authors of Redis even state this clearly).  Anything job-related where persistent storage is needed should use something like MongoDB, SQL, or the file system even (assuming you use backups).  You could use Redis for jobs, but you would have to use it on top of a persistent store, and at that point, your use case is 99% sure to be easier with the persistent store alone.

From my experience (in cases where I used SQL/Mongo vs. Redis for job storage/queues), the case of Redis always led to issues.  It also slows you down as a developer in my opinion, and anything that slows you down is against [my software principles](https://github.com/ladjs/lad#principles).  From querying to checking data, to finding that job data was erased due to shortened TTL's, or other weird behaviors, it always led to wasted time.

You could try using Redis/Bull I as did (quite intensely, having written my own wrappers around Bull - which is the only _decent_ Redis backed storage queue for Node.js, albeit it has core issues _still_, and is in general super confusing for end-users that aren't experts nor yet dug into internals of Bull).

I hit a tipping point, and wrote Bree to save myself (and you) the time and headaches.  I was extremely motivated to do this.

Using Bree will lead to cleaner code, less complexity, and no guesswork as to when your jobs will actually run.

**Comment by nullpaper** [comment]
> the case of Redis always led to issues.

@niftylettuce I'd be interested to know what these issues were. It sounds like you hit persistence issues? Was it anything else though? Notwithsanding any issues you personally hit, Redis can 100% be used as a primary store with multiple strategies for safe durability and persistence. You can [tune Redis](https://redis.io/docs/manual/persistence/) to literally _never_ lose any data even in catastrophic failure states.

In the purely hypothetical, if you were assured Redis was as safe as a the "persistent store", would your objection to it stand? (In which case could you be a bit more specific about those objections?)

Not questioning the issues with Bull/other tools, but more curious about what's behind the "Redis = bad for queues" vibe.
