### ISSUE TITLE
Passing data

### ISSUE THREAD

**Issue by DemGiran** [breejs/bree#19]
Hello, is there a way currently to pass data on to worker threads?

**Comment by dilizarov** [comment]
@niftylettuce It seems like bree is optimized for a use-case where you place jobs into a DB and then it works on them on some set interval.

My main use-case is for sending emails/notifications to users on-demand. I'd rather ask the worker to run with my passed in parameters (notification contents), than have to place something in the DB and then have the job process it.

Is there any way to pass metadata into a job on a job-by-job basis?

**Comment by shadowgate15** [comment]
Hi @DemGiran and @dilizarov,

You should be able to pass data to the worker using the workerData property.

For more information on the workerData property see: [Worker-Threads.workerData](https://nodejs.org/api/worker_threads.html#worker_threads_worker_workerdata)

[A crude example of passing workerData can be found in the tests.](https://github.com/breejs/bree/blob/b9bbd9f73867739e93aab912d27cd48536ff1005/test/test.js#L1289-L1309)

**Comment by dilizarov** [comment]
@shadowgate15 Thanks for the info.

So, I take it I'll probably have to use multiple Bree instances (`new Bree(...)`) for my use-case, yes?

My idea is to have one Bree that gets spun up for all the background jobs run every so often.

Then, for jobs that happen on demand and require data like above, I'll spin up a Bree instance to run it once.

Bree instances aren't expensive (resource-wise) to spin-up, right?

Or, should I have a singleton Bree instance that runs my scheduled jobs and sometimes runs jobs on demand?

**Comment by shadowgate15** [comment]
You do have access to the jobs array in Bree via `bree.config.jobs`. However, there would be no validation or setup like what happens during construction, when adding a job. This could lead to some issues when running the job. 
In order to use the above method, you could add the job to the `jobs` array and then use `bree.run('NAME_OF_JOB')` to run it.

It might be better for your use-case to setup a job for emails, notifications, etc. that listens for a message. The worker could then parse the message and perform the necessary actions. A basic example might look like [this](https://github.com/breejs/bree/blob/0b14ebecba54ef43fcdf8b2d9b43c658b321d24d/test/test.js#L494-L514) with [this worker](https://github.com/breejs/bree/blob/master/test/jobs/message.js).

**Comment by shadowgate15** [comment]
@dilizarov Did you get this to work for you?
