### ISSUE TITLE
[enhancement] Typescript support 

### ISSUE THREAD

**Issue by paularah** [breejs/bree#46]

**Comment by niftylettuce** [comment]
see https://github.com/breejs/bree/issues/41, https://github.com/breejs/bree/issues/24, https://github.com/breejs/bree/issues/3

TS is bad for open source, and is bad for the JavaScript community

**Comment by paularah** [comment]
Mind explaining why?

**Comment by ChronSyn** [comment]
It's your library, and your choice whether to support TS, but there's plenty of good reasons to support it:

- The ability to see what properties are available within my editor, without having to constantly swap to docs, saves a huge amount of time and reduces mistakes on first attempts to use it
- It's possible to generate a `.d.ts` file with definitions, even for regular JS projects using `dts-gen` (https://github.com/Microsoft/dts-gen). This doesn't require you to rewrite your project.
- You're actively going to turn people away from using the library by having such a hardline stance on it

As an example, this library seemed to support everything I wanted to, and had great docs, but the lack of typings makes in inefficient to use.

Due to this, it is not reasonable to claim that it is "the best job scheduler". It may do what you want it to, but if it is difficult or inefficient to implement it due to lack of typings or definitions, then I would say it is a far cry from the best.

Again, it's entirely your choice whether or not you support TS, but I completely disagree with the notion that it is bad for the community.

**Comment by JekRock** [comment]
I also would love to have the TypeScript support for this library, but I understand why the author doesn't want to add it.
It seems like Bree is using worker threads for Node. Worker threads support JavaScript only. Adding TypeScript would mean adding some limitations on how the library can be used in Node. For example, it won't work in a project that is started by ts-node or nodemon.
Just adding type definitions doesn't make much sense as previously described issues remain.
So, it seems like it's better not to add TypeScript support until Node supports TypeScript natively.

**Comment by niftylettuce** [comment]
TS = bloat
