### ISSUE TITLE
How to use with Meteor ?

### ISSUE THREAD

**Issue by ivonigC** [breejs/bree#94]
I'm trying to use the library with Meteor but somehow the jobs are not starting:

```
import { Meteor } from "meteor/meteor";
import Bree from "bree";
import Graceful from "@ladjs/graceful";

const bree = new Bree({
  jobs: [
    {
      name: "checkingjobs",
      interval: "5s",
    },
  ],
});

const graceful = new Graceful({ brees: [bree] });

Meteor.startup(function () {
  graceful.listen();
  bree.start();
});
```

In the same folder (./server) I have a jobs folder and a checkingjobs.js file with the following:

`
console.log("trigger jobs");
`

And I am getting the following error:

```
W20210226-13:37:45.664(1)? (STDERR) /Users/ivonig/.meteor/packages/meteor-tool/.1.10.2.p99aru.7e2ej++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20210226-13:37:45.665(1)? (STDERR)                                             throw(ex);
W20210226-13:37:45.666(1)? (STDERR)                                             ^
W20210226-13:37:45.681(1)? (STDERR) 
W20210226-13:37:45.682(1)? (STDERR) Error: ENOENT: no such file or directory, stat '/Users/ivonig/Collock/revolin/.meteor/local/build/programs/server/jobs'
W20210226-13:37:45.683(1)? (STDERR)     at Object.statSync (fs.js:932:3)
W20210226-13:37:45.685(1)? (STDERR)     at new Bree (/Users/ivonig/Collock/revolin/node_modules/bree/lib/index.js:180:24)
W20210226-13:37:45.688(1)? (STDERR)     at module (server/bree.js:187:14)
W20210226-13:37:45.689(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20210226-13:37:45.690(1)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20210226-13:37:45.690(1)? (STDERR)     at Module.moduleLink [as link] (/Users/ivonig/.meteor/packages/modules/.0.15.0.quoprd.p4uvg++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
W20210226-13:37:45.690(1)? (STDERR)     at module (server/main.js:1:1)
W20210226-13:37:45.691(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20210226-13:37:45.691(1)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20210226-13:37:45.692(1)? (STDERR)     at require (packages/modules-runtime.js:258:21)
W20210226-13:37:45.692(1)? (STDERR)     at /Users/ivonig/Collock/revolin/.meteor/local/build/programs/server/app/app.js:10099:15
W20210226-13:37:45.692(1)? (STDERR)     at /Users/ivonig/Collock/revolin/.meteor/local/build/programs/server/boot.js:401:38
W20210226-13:37:45.693(1)? (STDERR)     at Array.forEach (<anonymous>)
W20210226-13:37:45.693(1)? (STDERR)     at /Users/ivonig/Collock/revolin/.meteor/local/build/programs/server/boot.js:226:21
W20210226-13:37:45.693(1)? (STDERR)     at /Users/ivonig/Collock/revolin/.meteor/local/build/programs/server/boot.js:464:7
W20210226-13:37:45.693(1)? (STDERR)     at Function.run (/Users/ivonig/Collock/revolin/.meteor/local/build/programs/server/profile.js:280:14) {
W20210226-13:37:45.693(1)? (STDERR)   errno: -2,
W20210226-13:37:45.693(1)? (STDERR)   syscall: 'stat',
W20210226-13:37:45.695(1)? (STDERR)   code: 'ENOENT',
W20210226-13:37:45.695(1)? (STDERR)   path: '/Users/ivonig/Collock/revolin/.meteor/local/build/programs/server/jobs'
W20210226-13:37:45.695(1)? (STDERR) }
```

I tried to add root : false to the Bree constructor such as:
```

const bree = new Bree({
  root: false,
  jobs: [
    {
      name: "checkingjobs",
      interval: "5s",
    },
  ],
});
```

But I am then getting the following error:

W20210226-13:40:14.037(1)? (STDERR) Error: Job #1 named "checkingjobs" requires root directory option to auto-populate path

not sure what's the issue there but couldn't find any meteor integration. Thanks in advance.

**Comment by shadowgate15** [comment]
Without `root: false`, bree is looking for the file, however the file doesn't exist. Is `.meteor/local/build/programs/server/jobs` where the file is stored? If not, that is likely due to Meteor not copying the jobs folder during the build process which would make it an issue with Meteor or your configurations with Meteor. 

If you use `root:false`, every job needs it's own path.

**Comment by jankapunkt** [comment]
Wouldn't this be a good case for a bridge, so we can actually avoid using filesystem for persistence (but keep it as default implementation)?  I currently manage all data in my app through the DB and avoid FS at all, since in Meteor this can be a real struggle.

**Comment by shadowgate15** [comment]
I have a very rough understanding of the Meteor ecosystem, but, based on my understanding, you would run bree separately from Meteor and poll the database from the job to get the data.

I would say if you would like to create a Meteor integration that uses bree that would be fine.

**Comment by idmadj** [comment]
As @shadowgate15 mentioned, the `jobs` folder isn't present where Bree expects it. This is because Meteor's build system bundles code into a single file. 

You can use the `private` [special folder](https://guide.meteor.com/structure.html#special-directories) to instruct Meteor that you want the files in the `jobs` folder to be treated as static assets.

Create a folder named `private` at the root of your app, move your `jobs` folder there, then set `root: false` and specify each job's `path` using `Assets.absoluteFilePath`:
```js
import Bree from 'bree';

const bree = new Bree({
  root: false,
  jobs: [
    {
      name: "checkingjobs",
      path: Assets.absoluteFilePath('jobs/checkingjobs.js'),
      interval: "5s"
    }
  ]
});
```

You could also set `root` to `path.resolve('assets/app/jobs')` in the Bree options to avoid individually setting the path for each job, although it would break if the Meteor team ever changed where static assets are copied (AFAIK there is no documented way of getting that path):
```js
import Bree from 'bree';
import path from 'path';

const bree = new Bree({
  root: path.resolve('assets/app/jobs'),
  jobs: [
    {
      name: "checkingjobs",
      interval: "5s",
    },
  ],
});
```

Now, one big downside of this approach is that whatever code that runs from the static jobs folder is living in its own bubble. Since the rest of your Meteor app is bundled, there's no elegant way to import anything from your app or even from node_modules. You could hack around it by hardcoding paths, but that sounds like a nightmare to maintain. At that point it effectively makes more sense to just have a separate app running and interacting via the DB or an API.

**Comment by shadowgate15** [comment]
I think @idmadj has summed this up tremendously. If anybody wants to build a Meteor integration, we will gladly help in any way we can.
